### PR TITLE
Relax upper bound on `sqlalchemy`, to allow 2.0

### LINKED ISSUE #38: Support `sqlalchemy` 2
Hi, this is a great project. `sqlalchemy` 2 has been released, and it would be great if this supported it.

I'd be happy to open a PR.

### PR DESCRIPTION
**Pull request by dycw**
Resolves #38.

### CODE REVIEW

**Comment by lycantropos** [comment]
@dycw thanks, it looks like we need to merge #40 first since `Python3.6` is no longer supported by Github Actions (and in general)

and also it will require bumping minor version because we are going to add `Python3.11` & `SQLAlchemy>=2` support (which doesn't sound like a bugfix)

**Comment by lycantropos** [comment]
@dycw : I've already bumped version on your branch (sorry if it disturbs you), also added `mypy` support, let's merge once checks pass

**Comment by dycw** [comment]
Hi @lycantropos , sorry I think we're writing at the same time, and I've force pushed some stuff.

**Comment by lycantropos** [comment]
this should do, let's wait for checks to pass and merge it, after that we will release `v1.1.0`

**Comment by dycw** [comment]
Thanks for this great library again!

**Comment by lycantropos** [comment]
@dycw: you are welcome, thanks for your contribution

**Pull request merged**
